// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAdM-pXuFnxWVwue-LOxleFMX8LgzPGGA',
    appId: '1:203556319477:web:ec1a11374b3f67b8ba95bc',
    messagingSenderId: '203556319477',
    projectId: 'fir-flutter-codelab-831c0',
    authDomain: 'fir-flutter-codelab-831c0.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-831c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCrJuHdyYoPIPA5uKfwiWZN42QVO-B5o',
    appId: '1:203556319477:android:0948c575d46806d8ba95bc',
    messagingSenderId: '203556319477',
    projectId: 'fir-flutter-codelab-831c0',
    storageBucket: 'fir-flutter-codelab-831c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxThQ0-mi94csreWKVWKSyVi1aHniPCo',
    appId: '1:203556319477:ios:c92b4b3b16f4a6f0ba95bc',
    messagingSenderId: '203556319477',
    projectId: 'fir-flutter-codelab-831c0',
    storageBucket: 'fir-flutter-codelab-831c0.appspot.com',
    iosClientId: '203556319477-9j8qika88jur48d2er7b82msu36q6lrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSxThQ0-mi94csreWKVWKSyVi1aHniPCo',
    appId: '1:203556319477:ios:c92b4b3b16f4a6f0ba95bc',
    messagingSenderId: '203556319477',
    projectId: 'fir-flutter-codelab-831c0',
    storageBucket: 'fir-flutter-codelab-831c0.appspot.com',
    iosClientId: '203556319477-9j8qika88jur48d2er7b82msu36q6lrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
